#import <Foundation/Foundation.h>

#define AFPHOTO_BROWSER_WILL_TRANSITION @"AFPHOTO_BROWSER_WILL_TRANSITION"
#define AFPHOTO_BROWSER_DID_END_TRANSITION @"AFPHOTO_BROWSER_DID_END_TRANSITION"

@protocol AFPhoto <NSObject>







@end
