#import <Foundation/Foundation.h>

// TraitCollection Notifications
// 
#define AFPHOTOBROWSER_WILL_TRANSITION_TO_TRAINT_COLLECTION @"AFPHOTOBROWSER_WILL_TRANSITION_TO_TRAINT_COLLECTION"
#define AFPHOTOBROWSER_DID_TRANSITION_TO_TRAINT_COLLECTION @"AFPHOTOBROWSER_DID_TRANSITION_TO_TRAINT_COLLECTION"

@protocol AFPhoto <NSObject>







@end
